#!/usr/bin/env bash
# Post code-review findings as positioned discussions on a GitLab MR.
# Generated by the review-mr skill — fill the placeholders, then run:
#   GITLAB_TOKEN=glpat-... ./scripts/post-mr-<IID>-comments.sh [MR_IID]
set -euo pipefail

: "${GITLAB_TOKEN:?Set GITLAB_TOKEN (a token with 'api' scope)}"
MR_IID="${1:-__MR_IID__}"
PROJECT="__PROJECT__"   # URL-encoded path, e.g. group%2Fsubgroup%2Frepo
API="https://gitlab.com/api/v4/projects/${PROJECT}/merge_requests/${MR_IID}"

BASE_SHA="__BASE_SHA__"
HEAD_SHA="__HEAD_SHA__"

# Refuse to post if the MR's diff refs no longer match (wrong IID, or the MR
# was rebased/updated after these comments were anchored).
refs=$(curl -sf --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" "${API}" \
  | python3 -c 'import json,sys; d=json.load(sys.stdin)["diff_refs"]; print(d["base_sha"], d["head_sha"])')
if [ "$refs" != "${BASE_SHA} ${HEAD_SHA}" ]; then
  echo "diff_refs mismatch: MR !${MR_IID} has [$refs], expected [${BASE_SHA} ${HEAD_SHA}]." >&2
  echo "Wrong MR IID, or the MR was rebased/updated — regenerate the comments." >&2
  exit 1
fi

post_new() { # new_path new_line body  (comment on an added/changed line)
  curl -sf --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" -X POST "${API}/discussions" \
    --data-urlencode "position[position_type]=text" \
    --data-urlencode "position[base_sha]=${BASE_SHA}" \
    --data-urlencode "position[start_sha]=${BASE_SHA}" \
    --data-urlencode "position[head_sha]=${HEAD_SHA}" \
    --data-urlencode "position[new_path]=$1" \
    --data-urlencode "position[old_path]=$1" \
    --data-urlencode "position[new_line]=$2" \
    --data-urlencode "body=$3" > /dev/null && echo "posted: $1:$2"
}

post_old() { # old_path old_line body  (comment on a deleted line/file)
  curl -sf --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" -X POST "${API}/discussions" \
    --data-urlencode "position[position_type]=text" \
    --data-urlencode "position[base_sha]=${BASE_SHA}" \
    --data-urlencode "position[start_sha]=${BASE_SHA}" \
    --data-urlencode "position[head_sha]=${HEAD_SHA}" \
    --data-urlencode "position[new_path]=$1" \
    --data-urlencode "position[old_path]=$1" \
    --data-urlencode "position[old_line]=$2" \
    --data-urlencode "body=$3" > /dev/null && echo "posted (old): $1:$2"
}

post_note() { # body  (general, unpositioned MR discussion)
  curl -sf --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" -X POST "${API}/discussions" \
    --data-urlencode "body=$1" > /dev/null && echo "posted: general note"
}

# --- One call per comment below. Bodies are GitLab-flavored markdown. ---
# post_new  "src/path/file.css" 42 "🐛 **Title.** Body…"
# post_old  "src/deleted/file.scss" 8 "🐛 **Title.** Body…"
# post_note "🧹 **Title** (\`package.json:63\`). Body…"

echo "Done: posted discussions to MR !${MR_IID}."
